version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:8.11.2
    parallelism: 1
    working_directory: ~/mathgame/app
    steps:
      - checkout
      - attach_workspace:
          at: ~/mathgame/app
      - run: npm install
      - persist_to_workspace:
          root: .
          paths: dist
